[mypy]
packages = p3s
exclude = (?x)(
    control/.*$
    | converter/.*$
    | estimation/.*$
    | plotting/.*$
    | protection/.*$
    | diagnostic/.*$
    | create/.*$
  )
; test with the oldest supported version
python_version = 3.12
follow_imports = skip
allow_redefinition = true
disable_error_code = operator, call-overload

[mypy-nbmake.*]
ignore_missing_imports = true

[mypy-numba.*]
ignore_missing_imports = true

[mypy-plotly.*]
ignore_missing_imports = true

[mypy-scipy.*]
ignore_missing_imports = true

[mypy-pycuda.*]
ignore_missing_imports = true

[mypy-pandapower.*]
ignore_missing_imports = true

[mypy-networkx.*]
ignore_missing_imports = true
